POST /BarbeariaContext/Funcionarios
Content-Type: application/json

{
    "Nome": "João Silva",
    "CPF": "123.456.789-10",
    "Cargo": "Barbeiro",
    "Telefone": "(11) 91234-5678",
    "DataAdmissao": "2024-04-28"
}

GET /BarbeariaContext/Funcionarios

GET /BarbeariaContext/Funcionarios{id}

PUT /BarbeariaContext/Funcionarios/{id}
Content-Type: application/json

{
    "IdFuncionario": 1,
    "Nome": "João Nogueira",
    "CPF": "987.654.321-10",
    "Cargo": "Barbeiro",
    "Telefone": "(41) 99911-9988",
    "DataAdmissao": "28/03/2024"
}

DELETE /BarbeariaContext/funcionarios/{id}
