POST /BarbeariaContext/Servicos
Content-Type: application/json

{
    "Nome": "Corte de Cabelo Masculino",
    "Duracao": 30,
    "Preco": 30.00,
    "Descricao": "Corte de cabelo padrão para homens"
}

GET /BarbeariaContext/Servicos

GET /BarbeariaContext/Servicos/{id}

PUT /BarbeariaContext/Servicos/{id}
Content-Type: application/json

{
    "IdServico": 1,
    "Nome": "Barba",
    "Duracao": 45,
    "Preco": 40.00,
    "Descricao": "Barba na navalha"
}

DELETE /BarbeariaContext/Servicos/{id}
